[agent]
  interval = "15s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "N5mm205zSmBVu_asM-64g9UPAQMrNkntOmQA5hGYVaLr_4upNH267OV4mEaP8k_283k5e6uOriqRX86cxjbp7w=="
  organization = "Geothermal"
  bucket = "Temperatures"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["geothermal/data"]
  data_format = "influx"